name: Pip Verification

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  pip-verification:
    name: Pip Verification
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .