name: Stoneforge

on:
  push:
    branches: [ main,stoneforge0.1.6 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.12.1"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
      
    - name: Test with pytest
      run: |
        pytest
