name: Stoneforge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install numpy
      run: pip install numpy
      
    - name: Install pytest
      run: pip install pytest

    - name: Install scikit-learn
      run: pip install scikit-learn

    - name: Install xgboost
      run: pip install xgboost 
      
    - name: Test with pytest
      run: |
        pytest
