name: Stoneforge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: update pip
      run: python3 -m pip install --upgrade pip

    - name: install stoneforge
      run: pip install -e.
      
    - name: Test with pytest
      run: |
        pytest
