name: Stoneforge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.12.6"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
      
    - name: Test with pytest
      run: |
        pytest
